-- products:
CREATE TABLE norm_tables.products_temp AS
(
SELECT
	DISTINCT
	agt."ProduktnameName" AS product_name,
	agt."ProduktPreis" AS product_price,
	agt."Kategorie" AS category
FROM
	raw_tables.ausgangstabelle agt
ORDER BY
	agt."ProduktnameName"
);

ALTER TABLE norm_tables.products_temp 
	ADD COLUMN product_id INT PRIMARY KEY
		GENERATED BY DEFAULT AS IDENTITY;

-- category
CREATE TABLE norm_tables.categories_temp AS
(
SELECT
	DISTINCT
	agt."Kategorie" AS category
FROM
	raw_tables.ausgangstabelle agt
ORDER BY
	agt."Kategorie"
);

ALTER TABLE norm_tables.categories_temp
	ADD COLUMN category_id INT PRIMARY KEY
		GENERATED BY DEFAULT AS IDENTITY;

-- customers
CREATE TABLE norm_tables.customers_temp AS
(
SELECT
	DISTINCT
	agt."Nachname" AS last_name,
	agt."Vorname" AS first_name,
	agt."KundeKreditkarte" AS ccn,
	agt."KundeAdresse" AS address
FROM
	raw_tables.ausgangstabelle agt
ORDER BY
	agt."Nachname"
);

ALTER TABLE norm_tables.customers_temp
	ADD COLUMN customer_id INT PRIMARY KEY
		GENERATED BY DEFAULT AS IDENTITY;

-- orders
CREATE TABLE norm_tables.orders_temp AS
(
SELECT
	agt."KundeAdresse" address,
	agt."ProduktnameName" AS product_name,
	agt."Menge" AS quantity,
	agt."Bestelldatum" AS order_date
FROM
	raw_tables.ausgangstabelle agt
ORDER BY
	agt."Bestelldatum"
);

ALTER TABLE norm_tables.orders_temp
	ADD COLUMN order_id INT PRIMARY KEY
		GENERATED BY DEFAULT AS IDENTITY;

-- addresses
CREATE TABLE norm_tables.addresses_temp AS
(
SELECT
	DISTINCT
	agt."KundeAdresse" AS address,
	agt."Straße" AS street_address,
	agt."Postleitzahl" AS zip_code,
	agt."Stadt" AS city
FROM
	raw_tables.ausgangstabelle agt
ORDER BY
	agt."Stadt"
);

ALTER TABLE norm_tables.addresses_temp
	ADD COLUMN address_id INT PRIMARY KEY
		GENERATED BY DEFAULT AS IDENTITY;

-- tables erstellen/sortieren mit PK, FK, seqences,

-- products
CREATE TABLE core.products AS
(
SELECT
	p.product_id,
	p.product_name,
	p.product_price,
	ca.category_id
FROM
	norm_tables.products_temp p
JOIN norm_tables.categories_temp ca
		USING (category)
);

-- categories
CREATE TABLE core.categories AS
(
SELECT
	ca.category_id,
	ca.category AS category_name
FROM
	norm_tables.categories_temp ca
);

-- customers
CREATE TABLE core.customers AS
(
SELECT
	cu.customer_id,
	cu.last_name,
	cu.first_name,
	a.address_id,
	cu.ccn
FROM
	norm_tables.customers_temp cu
JOIN norm_tables.addresses_temp a
		USING (address)
);

-- orders
CREATE TABLE core.orders AS
(
SELECT
	o.order_id,
	cu.customer_id,
	p.product_id,
	o.quantity,
	o.order_date
FROM
	norm_tables.orders_temp o
JOIN norm_tables.customers_temp cu
		USING (address)
JOIN norm_tables.products_temp p
		USING (product_name)
ORDER BY o.order_date
); 

--addresses
CREATE TABLE core.addresses AS
(
SELECT
	a.address_id,
	a.street_address AS address,
	a.zip_code,
	a.city
FROM
	norm_tables.addresses_temp a
);

-- PK, FK, constraints, dtype, references

-- products
ALTER TABLE core.products
ALTER COLUMN product_name SET NOT NULL,
ALTER COLUMN product_price SET NOT NULL,
ALTER COLUMN category_id SET NOT NULL,
ALTER COLUMN product_price SET DATA TYPE NUMERIC(10,2),
ADD CONSTRAINT pk_product_id PRIMARY KEY (product_id);

CREATE SEQUENCE core.product_id_seq;

ALTER TABLE core.products
ALTER COLUMN product_id SET DEFAULT nextval('core.product_id_seq');

SELECT setval('core.product_id_seq', 42);

-- category
ALTER TABLE core.categories
ALTER COLUMN category_name SET NOT NULL,
ADD CONSTRAINT pk_category_id PRIMARY KEY (category_id);

CREATE SEQUENCE core.category_id_seq;

ALTER TABLE core.categories
ALTER COLUMN category_id SET DEFAULT nextval('core.category_id_seq');

SELECT setval('core.category_id_seq', 19);

-- customers
ALTER TABLE core.customers
ALTER COLUMN last_name SET NOT NULL,
ALTER COLUMN first_name SET NOT NULL,
ALTER COLUMN address_id SET NOT NULL,
ALTER COLUMN ccn SET NOT NULL,
ADD CONSTRAINT pk_customer_id PRIMARY KEY (customer_id);

CREATE SEQUENCE core.customer_id_seq;

ALTER TABLE core.customers
ALTER COLUMN customer_id SET DEFAULT nextval('core.customer_id_seq');

SELECT setval('core.customer_id_seq', 30);

-- orders
ALTER TABLE core.orders
ALTER COLUMN customer_id SET NOT NULL,
ALTER COLUMN product_id SET NOT NULL,
ALTER COLUMN quantity SET NOT NULL,
ALTER COLUMN order_date SET NOT NULL,
ADD CONSTRAINT pk_order_id PRIMARY KEY (order_id);

CREATE SEQUENCE core.order_id_seq;

ALTER TABLE core.orders
ALTER COLUMN order_id SET DEFAULT nextval('core.order_id_seq');

SELECT setval('core.order_id_seq', 100);

-- addresses
ALTER TABLE core.addresses
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN zip_code SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ADD CONSTRAINT pk_address_id PRIMARY KEY (address_id);

CREATE SEQUENCE core.address_id_seq;

ALTER TABLE core.addresses
ALTER COLUMN address_id SET DEFAULT nextval('core.address_id_seq');

SELECT setval('core.address_id_seq', 30);

-- references

-- products
ALTER TABLE core.products
ADD CONSTRAINT fk_category_id FOREIGN KEY (category_id) REFERENCES core.categories(category_id);

-- categories hat keinen fk und keine referencesd

-- customers
ALTER TABLE core.customers
ADD CONSTRAINT fk_address_id FOREIGN KEY (address_id) REFERENCES core.addresses(address_id);

-- orders
ALTER TABLE core.orders
ADD CONSTRAINT fk_customer_id FOREIGN KEY (customer_id) REFERENCES core.customers(customer_id),
ADD CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES core.products(product_id);

-- addresses hat keinen fk und keine references