CREATE TABLE norm_tables.orders_temp AS
(
SELECT
	agt."KundeAdresse" address,
	agt."ProduktnameName" AS product_name,
	agt."Menge" AS quantity,
	agt."Bestelldatum" AS order_date
FROM
	raw_tables.ausgangstabelle agt
ORDER BY
	agt."Bestelldatum"
);

ALTER TABLE norm_tables.orders_temp
	ADD COLUMN order_id INT PRIMARY KEY
		GENERATED BY DEFAULT AS IDENTITY;

CREATE TABLE core.orders AS
(
SELECT
	o.order_id,
	cu.customer_id,
	p.product_id,
	o.quantity,
	o.order_date
FROM
	norm_tables.orders_temp o
JOIN norm_tables.customers_temp cu
		USING (address)
JOIN norm_tables.products_temp p
		USING (product_name)
ORDER BY o.order_date
);

ALTER TABLE core.orders
ALTER COLUMN customer_id SET NOT NULL,
ALTER COLUMN product_id SET NOT NULL,
ALTER COLUMN quantity SET NOT NULL,
ALTER COLUMN order_date SET NOT NULL,
ADD CONSTRAINT pk_order_id PRIMARY KEY (order_id);

CREATE SEQUENCE core.order_id_seq;

ALTER TABLE core.orders
ALTER COLUMN order_id SET DEFAULT nextval('core.order_id_seq');

SELECT setval('core.order_id_seq', 100);

ALTER TABLE core.orders
ADD CONSTRAINT fk_customer_id FOREIGN KEY (customer_id) REFERENCES core.customers(customer_id),
ADD CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES core.products(product_id);